### ISSUE TITLE
Show Panel on per page/project basis (not always on every page)

### ISSUE THREAD

**Issue by lirtistan** [leonvogt/hotwire-dev-tools#22]
Hi,

a wish from me. The plugin is nice, but whould be better to just show the panel (bottom right) on per page/project basis (not on every page/tab opened in the browser)!?

I dont know how complicated it is to implement, such a behavior. The browser own devtools panel does this already, maybe worth a visit on there solution.

Thanks.

**Comment by leonvogt** [comment]
Hi @lirtistan,

I feel the same way, it would be great to save the options on a per page basis.    
Maybe we should also differentiate between "user global defaults" and "user page specific settings".    
I didn't found a good way to do it yet, but I'll keep looking.
For sure a must-have in the future.

**Comment by lirtistan** [comment]
I just add some considerations here and there, for later use....

* Google Chrome
  - has a storage API, maybe thats a way to persist things, see https://developer.chrome.com/docs/extensions/reference/api/storage?hl=en it's a storage API similar to localStorage and IndexedDB, just for extensions.
  - you can inspect the TabID of the current visited page within https://developer.chrome.com/docs/extensions/reference/api/devtools/inspectedWindow?hl=en

* Firefox 
  - also has a storage API for extensions, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage
  - has the same feature as Chrome, to inspect Tabs and there corresponding ID with https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API, see `browser.tabs`

**Comment by leonvogt** [comment]
I'm not sure about the tab ID, to be honest.
I feel like when we want to scope the options on a per-page basis, we should consider using the origin _(example.com)_ as an identifier. This way, we would be independent of an alternating tab ID.

Some questions I have about page-specific settings:
- how can we visualize and distinguish between global user settings and page-specifics
- if we, for some reason, reach the [limit of 10 MB](https://developer.chrome.com/docs/extensions/reference/api/storage#properties_2) (even though it's unrealistic) how can the user delete and manage page-specific settings?

I guess it's mostly a user oriented GUI question for me.

**Comment by lirtistan** [comment]
> I'm not sure about the tab ID, to be honest. I feel like when we want to scope the options on a per-page basis, we should consider using the origin _(example.com)_ as an identifier. This way, we would be independent of an alternating tab ID.

the tabID was just a first idea i came up with, i didn't nailed it down to use only that. 
the bigger question is, i there a solution how we can differentiate between all the local running dev setups, because they have all a URL like http://localhost:PORT/whatever/route !?

> Some questions I have about page-specific settings:
> 
> * how can we visualize and distinguish between global user settings and page-specifics

i thought about using the URL as a identifier, so if i click on "Show Panel" it remembers the current page URL and injects the panel stuff only on that page.

> * if we, for some reason, reach the [limit of 10 MB](https://developer.chrome.com/docs/extensions/reference/api/storage#properties_2) (even though it's unrealistic) how can the user delete and manage page-specific settings?

the docs said that `unlimitedStorage` permission needs to be granted in the manifest, therefore just the sky is the limit :)

```json
"permissions": ["storage", "unlimitedStorage"]
```

deletion should happen if the tab/window for that url is closed.

**Comment by lirtistan** [comment]
just for documentation, the plugin can get to all available/opened tabs with `chrome.tabs.query()` method, but we need to set the permission `"host_permissions"` inside the manifest.json like this...

```json manifest.json
"host_permissions": [ "<all_urls>" ]
```

Now we can access all tabs with...

```js popup.js
(async () => {
  const tabs = await chrome.tabs.query({
    url: [
      "http://*:*/*",
      "https://*:*/*",
      "file:///*"
    ]
  })

  console.log( tabs )
})()
```
...which gives us...

![Screenshot from 2024-06-06 12-08-30](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/48079c5c-f3c3-4512-9548-62b23706a509)

**Comment by leonvogt** [comment]
Hi @lirtistan,

Thanks for all your suggestions!
I've put up a [pull request](https://github.com/leonvogt/hotwire-dev-tools/pull/27) that will introduce page-specific options.    
Inspired by some of your ideas like:

> ```js
> chrome.tabs.query({ currentWindow: true, active: true }, function( tabs ) {
>     console.log( tabs[0] )
> })
> ```

I'll have to go over it and refactor some of the stuff before merging it, but i think we can introduce this behaviour in the next release.

**Comment by lirtistan** [comment]
Alright, ty so much.

**Comment by leonvogt** [comment]
Also, just to document it here:   
I mentioned my question about the storage limit of 10 MB in this issue.   
Quick math shows we don't really need to worry about this.   

We currently saving around 600 bytes. Let's go with 1'000 bytes if you have some long blacklists.   
[10485760](https://developer.chrome.com/docs/extensions/reference/api/storage#properties_3) / 1000 = 10'485.   
So the user can save up to 10'484 page-specific options (-1 for the global one).    
Guess there is nothing to worry about right now. At least not at this point.
