### ISSUE TITLE
Add a checkbox option for console logging of stream events

### ISSUE THREAD

**Issue by lirtistan** [leonvogt/hotwire-dev-tools#24]
Hi,

another cool idea is to add a checkbox for logging of stream events, thus we dont need to write own debug code.

**Comment by leonvogt** [comment]
Hi @lirtistan,

Thanks for opening this!
This sounds like a good enhancement for monitoring Turbo Streams without needing to open the detail panel.    
Would you like to give this a go, or should I do it in the next few days?

**Comment by lirtistan** [comment]
Hi @leonvogt ,

RN i do some investigatigation about the tab/url remembering on issue #22 , extensions are not my business and you are more familiar with browser extensions, so whould be better you take this.

Sorry, i know iam not very helpful RN.

**Comment by leonvogt** [comment]
@lirtistan, thanks for this good suggestion!    
This feature was merged in #26.
