### ISSUE TITLE
CSS for the checkbox (switch style) elements inside popup.html need 'user-select: none'

### ISSUE THREAD

**Issue by lirtistan** [leonvogt/hotwire-dev-tools#29]
Hi Leon,

as the Title mentioned already, i discovered some issues whilst iam accidentally selected some text during click on the checkbox (switch) elements inside the popup.html, see screenshot below.

![Screenshot from 2024-06-09 11-15-42](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/fb8a452d-561c-40a6-9170-4af4d52391a1)

**Comment by leonvogt** [comment]
Good catch! Thank you @lirtistan!
