### ISSUE TITLE
Icon visibility in dark mode browser

### ISSUE THREAD

**Issue by janpeterka** [leonvogt/hotwire-dev-tools#31]
Hi, I just installed this extension, and I have hard time seeing it in my toolbar in dark mode browser. It's just a minor annoyance, nothing serious, but if it's possible to maybe have different icon for dark mode, or make icon work in both modes (maybe black lightning bolt with white outline would work?), it would be neat :)

![Screenshot from 2024-06-10 10-32-29](https://github.com/leonvogt/hotwire-dev-tools/assets/6343648/3110c43d-cf0e-42cc-88bc-f2cae1d312f9)

**Comment by lirtistan** [comment]
Working on it RN, thanks for mention that.

**Comment by leonvogt** [comment]
Thanks for reporting @janpeterka!    
It really is hard to spot on a dark background.    
Black lightning bolt with white outline, sounds good to me 👍

**Comment by janpeterka** [comment]
Amazing, thank you!
