### ISSUE TITLE
inject.js got injected on all WebSites, no matter if "Show Panel" is toggled or not

### ISSUE THREAD

**Issue by lirtistan** [leonvogt/hotwire-dev-tools#44]
Hi,

seems inject.js got inject on all Sites by default, iam not sure if this is intentionally. Other plugins eg. [Livereload](https://github.com/livereload/livereload-extensions) inject things on user action, not by default.

Affected version: 0.2.1
(Screenshots where made within version 0.2.0, but issue still exist)
 
![Screenshot from 2024-06-13 07-34-50](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/3e03581f-a145-4c98-98bd-46dff18e71cb)

![Screenshot from 2024-06-13 07-36-13](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/4b7f11c3-7840-4c3f-bfff-2ab04f8f8d06)

**Comment by leonvogt** [comment]
Hi @lirtistan, yes that's a good point.   
We don't really need to inject the script, when the detail panel isn't open.     

When I look at your screenshot, I'm also wondering if we should rename it to something more explicit like "hotwire_dev_tools_inject_script.js".   
So it's easier to spot from where the script is coming from.
