### ISSUE TITLE
Shortcut Alt+Shift+A doesn't seem to work in Chrome

### ISSUE THREAD

**Issue by lirtistan** [leonvogt/hotwire-dev-tools#48]
Hi,

as the title already mentioned, the shortcut doesn't work. I tried in Chrome Version 125.0.6422.141 (Official Build) (64-bit) 

![Screenshot from 2024-06-14 13-23-08](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/0ce16ad9-a706-4076-95ba-7d81493711b1)

In Firefox it worked.

**Comment by leonvogt** [comment]
Hi, 

I just tried the shortcut in a fresh Chrome profile. It works for me.    
Version 126.0.6478.62 (Official Build) (arm64) - macOS

Is it possible that another installed extension has already defined `Alt+Shift+A`?    
You can check this under `chrome://extensions/shortcuts`

If not, it would be interesting to know if it works for you, if you define some other custom shortcut.


![image](https://github.com/leonvogt/hotwire-dev-tools/assets/17851143/197336db-9318-4a8c-bf1c-33cd0e47b4e3)

**Comment by lirtistan** [comment]
No other shortcuts defined, see here...

![Screenshot from 2024-06-14 16-46-42](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/29571078-119a-4e2d-9a01-8251e9184254)


If i change to Ctrl+Shift+A then it works.

**Comment by lirtistan** [comment]
I found the issue, `Alt+Shift+A` doesn't work because it's bound by chrome itself. So we need another shortcut just for chrome or a shortcut which works for all browsers.

See here, those are the list of Chrome shortcuts, bound to himself...
https://support.google.com/chrome/answer/157179#zippy=%2Cgoogle-chrome-feature-shortcuts

I also searched in the System Settings of my (OS) for a shortcut bound to `Alt+Shift+A` but didn't found one, seems we are safe on this site.

**Comment by lirtistan** [comment]
Btw, i don't know if this was intentionaly but the chrome extension docs also mention to use `"default"` as target inside the manifest.json so...

```json
{
  "commands": {
    "_execute_action": {
      "suggested_key": {
        "default": "Alt+Shift+A",
        "windows": "Alt+Shift+A",
        "mac": "Alt+Shift+A",
        "chromeos": "Alt+Shift+A",
        "linux": "Alt+Shift+A"
      }
    }
  }
}
```

...becomes...

 ```json
{
  "commands": {
    "_execute_action": {
      "suggested_key": {
        "default": "Alt+Shift+A"
      }
    }
  }
}
```

..and that should work for all browser, OS keys should just be added as a weighted option, to become a exception on that specific platform.

I can't really say if this is working cross-platform, need maybe more investigation first, just wana to mention.

**Comment by leonvogt** [comment]
> I found the issue, Alt+Shift+A doesn't work because it's bound by chrome itself. So we need another shortcut just for chrome or a shortcut which works for all browsers.

Hm strange, the shortcut works on my chrome version. Are you maybe using a different OS than me, like Windows or Linux?    
I would be happy to find another shortcut that works on all browsers and OS and replace the current one with it.   

Also, thank you very much for pointing out the `default` option in the manifest!   
Seems like a reasonable change as soon as we found a shortcut that works on all the different OS.

**Comment by lirtistan** [comment]
Iam on Linux, sure can be different on other OSes, i don't know.

**Comment by leonvogt** [comment]
> If i change to Ctrl+Shift+A then it works.

For some reasons, Ctrl+Shift+A doesn't seem to work for me on macOS.    
I've changed i to Alt+Shift+S. This doesn't seem to be on the reserved list of shortcuts from [firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly), [chrome](https://support.google.com/chrome/answer/157179?sjid=10113784585767453700-EU) or [safari](https://support.apple.com/guide/safari/keyboard-and-other-shortcuts-cpsh003/mac).

Alt+Shift+S works for me on macOS on all three browsers.   
Would you mind testing if it works for you as well on Linux?

**Comment by lirtistan** [comment]
Sure give me 5mins.

**Comment by lirtistan** [comment]
Yep that works.

**Comment by leonvogt** [comment]
Awesome, thank you!   
Just tested it on Windows with Firefox and Chrome. Worked there too 🥳
