### ISSUE TITLE
popup.js throws a URL related error on opening Inspector (using the menu entry)

### ISSUE THREAD

**Issue by lirtistan** [leonvogt/hotwire-dev-tools#49]
Hi,

during bug hunting on #47 , i found a new bug in popup.js (see Screenshots on Line 291)... 

![Screenshot from 2024-06-14 20-57-56](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/48f57ae0-f65f-4b1e-bbea-b59b7830fef6)

![Screenshot from 2024-06-14 21-01-01](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/53eeb309-ee99-4123-952d-ef52814d17ea)

that bug appeared inside my Chrome Version 125.0.6422.141 (Official Build) (64-bit), if i use the right click menu on the extension icon to visit `Inspect popup`, see Screenshot below...

   
![Screenshot from 2022-09-05 17-45-26](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/7512ff66-c63e-45bc-aa23-4edbc488ea95)

**Comment by lirtistan** [comment]
Btw it just appears if you open the Inspector with a click on the menu entry, it **doesn't appear** if you right click inside the already opened popup.html.

**Comment by leonvogt** [comment]
Hi @lirtistan,   

Thanks for reporting this.   
I just merged #50 which should resolve this issue.    
Would you mind giving this a try and see if it resolves this issue?

**Comment by lirtistan** [comment]
I do gime a minute

**Comment by lirtistan** [comment]
It works now, error is gone. Tyvm ❤️

**Comment by leonvogt** [comment]
Awesome, thank you @lirtistan!
