### ISSUE TITLE
Indicate that a Turbo Frame has been updated

### ISSUE THREAD

**Issue by leonvogt** [leonvogt/hotwire-dev-tools#51]
It would be nice to have a visual indication that a Turbo Frame has been updated.    
We could probably use a MutationObserver to monitor the `busy` and `completed` attribute on the frame, as [documented here](https://turbo.hotwired.dev/reference/frames#html-attributes).    
Or maybe even listen to the [turbo:frame-render](https://turbo.hotwired.dev/reference/events#turbo%3Aframe-render) event.

**Comment by lirtistan** [comment]
I think its easier to go with the `turbo:frame-render` event, because we can simply add a css (quick flash animation or so) to the turbo frame and remove that after a short while?

To be fair, a MutationObserver is maybe easier to manage but more code (more possible bugs).

**Comment by leonvogt** [comment]
Yes, I also think listening to the `turbo:frame-render` event is the way to go for now.      
I have some plans for the future, where it would be handy to know when the Turbo Frame starts a new request, but for now I agree that we should go the easiest way.
