### ISSUE TITLE
"Monitor Events" seems always active on all sites and can't be disabled

### ISSUE THREAD

**Issue by lirtistan** [leonvogt/hotwire-dev-tools#68]
Hi,

it seems "Monitor Events" is now active on all site by default and c an't be deactivated. I tried to disable it, i closed the site and opened it again and "Monitor Events" is active again.

**Comment by leonvogt** [comment]
Hi @lirtistan, thanks for opening this issue.
I tried to reproduce the issue and found out, that the "Monitor Events" toggle doesn't properly remove the selected events and instead just hides them.    
When I deselect all events and then toggle the "Monitor Events" switch off, it works as expected.     

Is this the same behavior you are experiencing?    
I'll try to fix this as soon as possible.

**Comment by lirtistan** [comment]
Hi Leon,

yes confirmed, i tried on my linux box RN, same behavior u described.
> I'll try to fix this as soon as possible.
I know u will. ❤️
