### ISSUE TITLE
preview of highlight color in menu

### ISSUE THREAD

**Issue by MarchandMD** [leonvogt/hotwire-dev-tools#85]
Might be nice to visually reference what the hex code actually looks like when clicking the extension icon

**Comment by leonvogt** [comment]
Hi @MarchandMD, thanks for opening this issue.

100%, this would be great!       
I'm guessing you're on Firefox, right?
We had a color picker in the popup at one time, but there were [some issues with it on Firefox](https://github.com/leonvogt/hotwire-dev-tools/issues/20), so I removed the picker in the Firefox version.       

I'll check for some other approaches to get the color picker to work, or at least show a preview as you suggested.

**Comment by MarchandMD** [comment]
Oh shoot; I should have explored the other issues before suggesting. Yep am on FF

**Comment by leonvogt** [comment]
No you're absolutely right! The current experience on Firefox isn’t very user-friendly and we should try to improve it.
Thanks for highlighting it

**Comment by leonvogt** [comment]
Hi @MarchandMD 
I've just released a new version that includes a color preview for Firefox.   
Let me know if you encounter any issues.
