### ISSUE TITLE
Incorrect warnings on elements with multiple controllers

### ISSUE THREAD

**Issue by mtownsend81** [leonvogt/hotwire-dev-tools#88]
I have an element that has multiple controllers - and I'm getting `The Stimulus target is not inside the Stimulus controller` warnings.

The `_checkStimulusTargetsNesting` method in `src/lib/diagnostics_checker.js` is only looking for a parent element that is an _exact_ match for the controller name - rather than allowing an element to have multiple controllers such as `<body data-controller="search list-selection">`

**Comment by leonvogt** [comment]
Uh good catch, thank you @mtownsend81!   
A total blunder on my part.
I'll try to fix it as soon as possible.   
Thanks for reporting!

**Comment by leonvogt** [comment]
Hi @mtownsend81, I've just publish a new version that should fix this issue.   
Let me know if you encounter any other problems.
