### ISSUE TITLE
Uncaught ReferenceError: TURBO_FRAME_OVERLAY_CLASS_NAME is not defined

### ISSUE THREAD

**Issue by DawidJanczak** [leonvogt/hotwire-dev-tools#92]
Hello,

We're getting the error above when using this extension. This seems to happen only on lazily-loaded turbo frames: we have some code that opens a modal that contains a turbo frame with `loading="lazy"` and a `src` attribute. As soon as the frame contents get loaded this error gets thrown from the extension. Full trace:
```
hotwire_dev_tools_content.js:115 Uncaught ReferenceError: TURBO_FRAME_OVERLAY_CLASS_NAME is not defined
    at zn (hotwire_dev_tools_content.js:115:6566)
    at async FrameController.loadResponse (turbo.es2017-esm.js:5931:1)
    at async FrameController.requestSucceededWithResponse (turbo.es2017-esm.js:6006:1)
```

**Comment by leonvogt** [comment]
Hi @DawidJanczak 

Thanks for reporting this issue!
I've never seen this issue before. I will look into it and let you know as soon as I know more

**Comment by DawidJanczak** [comment]
Thank you, let me know if you need any more details from us :)

**Comment by leonvogt** [comment]
Hi @DawidJanczak, I've spotted the error, was a total oversight on my part. The PR #94 should fix the issue.
I'll release a new version of the extension in the coming days.
