### ISSUE TITLE
Uppercase Turkish char opens up the modal

### ISSUE THREAD

**Issue by ogirginc** [leonvogt/hotwire-dev-tools#99]
The `option + shift + s` shortcut clashes with the upcase `ş`, which happens when the user tries to write `Ş`.

Nothing major, but it would be nice to turn off the shortcut :)

https://record.ogirginc.com/watch/e1bedd10-1ab5-4951-9993-781ce6c22d84

**Comment by leonvogt** [comment]
Hi @ogirginc,

I'm sorry to hear that the shortcut is causing you trouble.
You should be able to disable or customize the shortcut in the global extension settings of your browser.
From the video you shared, it seems that you are using Arc. The shortcut can be changed at  `arc://extensions/shortcuts`.   

![screenshot 2024-12-26 at 12 59 44@2x](https://github.com/user-attachments/assets/fe738acc-5ca5-40c9-b64f-02997b24ea7a)

Note: I needed to restart the browser for the changes to take effect.
Please feel free to reopen this issue if you continue to encounter any problems.

**Comment by ogirginc** [comment]
Oops. I have only checked the extension itself. Apologies for wasting your time 😅

**Comment by leonvogt** [comment]
No worries, you didn't!
Maybe we should add a note to the readme, since it really is kind of a hidden thing.
